version: '3.8'

services:

  db:
    image: postgres:14.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
#    ports:
#      - 1337:5432
    env_file:
      - ./web/.env.db

  web:
    build: ./web
    command: gunicorn web.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./web/.env
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data: